name: sync-chinnkarahoi-scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-lxk0301-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync chinnkarahoi-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chinnkarahoi/jd_scripts.git"
          source_branch: "master"
          destination_branch: "chinnkarahoi"
          github_token: ${{ secrets.PAT }}
          
      - name: sync lan-tianxiang-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lan-tianxiang/JS_TOOL.git"
          source_branch: "A1"
          destination_branch: "lan-tianxiang"
          github_token: ${{ secrets.PAT }}
          
      - name: sync supermanito-main-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zt6/github_SuperManito_JD-FreeFuck.git"
          source_branch: "main"
          destination_branch: "supermanito-main"
          github_token: ${{ secrets.PAT }}
          
      - name: sync supermanito-source-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zt6/github_SuperManito_JD-FreeFuck.git"
          source_branch: "source"
          destination_branch: "supermanito-source"
          github_token: ${{ secrets.PAT }}
